language: node_js
node_js:
  - "stable"
install:
  - npm install -g firebase-tools
deploy:
  skip_cleanup: true
  on:
    branch: advance-auto-deploy
  script:
    - echo "Deploying!!"
    - firebase deploy --project $PROJECT_ID --token $FIREBASE_TOKEN
after_success:
  script:
    - echo "Deployed!!"