language: node_js
node_js:
  - "stable"
install:
  - npm install -g firebase-tools
deploy:
  - provider: script
    script:
      - firebase deploy --project $PROJECT_ID --token $FIREBASE_TOKEN
    on:
      branch: advance-auto-deploy