language: node_js
node_js:
  - "stable"
install:
  - npm install -g firebase-tools
deploy:
  - provider: script
    script:
      # $PROJECT_ID, $FIREBASE_TOKEN are variables ENVs configured on travis-ci
      - firebase deploy --project $PROJECT_ID --token $FIREBASE_TOKEN
    on:
      # Clone source from advance-auto-deploy branch
      branch: advance-auto-deploy